### PR TITLE
Slightly improve `wafris-rb` response time.

### PR DESCRIPTION
**Pull request by ruyrocha**
The tests were performed using [Siege](https://github.com/JoeDog/siege), e.g:

**main branch:**
```
Transactions:                  12500 hits
Availability:                 100.00 %
Elapsed time:                  88.44 secs
Data transferred:             143.84 MB
Response time:                  0.18 secs
Transaction rate:             141.34 trans/sec
Throughput:                     1.63 MB/sec
Concurrency:                   24.96
Successful transactions:       12500
Failed transactions:               0
Longest transaction:            1.04
Shortest transaction:           0.01
```

**this branch:**
```
Transactions:                  12500 hits
Availability:                 100.00 %
Elapsed time:                  81.33 secs
Data transferred:             143.84 MB
Response time:                  0.16 secs 
Transaction rate:             153.69 trans/sec
Throughput:                     1.77 MB/sec
Concurrency:                   24.97
Successful transactions:       12500
Failed transactions:               0
Longest transaction:            0.37
Shortest transaction:           0.02
```

Some points to consider:

- [ ] update the docs on how to use `hiredis`
- [ ] remove the log suppressor
- [ ] add any missing specs

### CODE REVIEW

**Comment by ruyrocha** [comment]
@rmcastil, here is the PR with some changes for the gem.

I think I may be missing something due to the difference on numbers for the object allocations, and the overall speed was slightly improved.

I checked the local Redis server and didn't find anything obvious that would be impacting on performance, and I didn't look at the Lua part.

**Comment by ruyrocha** [comment]
hey @rmcastil, what are your thoughts on this? Perhaps I can break it down into smaller PRs.

**Comment by ruyrocha** [comment]
@rmcastil :+1: here for the other small PRs.

I'm pretty sure timeouts and connection pooling are safe, but is the core (Lua part) up to date so I can double-check the Redis commands?

**Comment by rmcastil** [comment]
Lua core is up to date but as long as eval works it should be good.
What’s the big benefit of the library?

On February 12, 2024, GitHub ***@***.***> wrote:
> @rmcastil <https://github.com/rmcastil> 👍 here for the other small
> PRs.
>
> I'm pretty sure timeouts and connection pooling are safe, but is the
> core (Lua part) up to date so I can double-check the Redis commands?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/Wafris/wafris-rb/pull/69#issuecomment-1940251457>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AABF6M3YWHWYIVQ7XWMTQMTYTLD6NAVCNFSM6AAAAABBG2XRJOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBQGI2TCNBVG4>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by ruyrocha** [comment]
@rmcastil the main reasoning for speed is around the implementation (C vs Ruby).

There's this [public benchmark](https://github.com/redis/hiredis-rb?tab=readme-ov-file#benchmarks) from a while ago, and this [other one](https://gist.github.com/jgaskins/ecc0fc90d78cdec63c31e0ce5544faa1#file-output-m1-txt) with recent hardware but not so conclusive; I'm only stating they're not conclusive based on Redis commands for the implementation using `TCPSocket`.

**Comment by ruyrocha** [comment]
@rmcastil I keep asking myself what would be the best strategy to check the whole outcome, and I think Siege can simplify it; do you have any other suggestions to test the changes? They involve loading the middleware early on Rails, and the usage of `hiredis`.

**Comment by rmcastil** [comment]
Closing this as it's not critical to the future of core. Plus we've been discussing a different architecture approach internally.

**Pull request closed without merging**
